#+TITLE: Teoten
#+NICK: teoten
#+DESCRIPTION: Trying out org social
#+AVATAR: https://blog.teoten.com/img/tt-avatar.jpg
#+LINK: https://teoten.com
#+LINK: https://blog.teoten.com

#+FOLLOW: https://andros.dev/static/social.org
#+FOLLOW: https://rossabaker.com/social.org
#+FOLLOW: https://omidmash.de/social.org
#+FOLLOW: https://johnhame.link/social.org
#+FOLLOW: https://eoin.site/social.org
#+FOLLOW: https://adsan.dev/social.org
#+FOLLOW: https://emillo.net/social.org
#+FOLLOW: https://cmdln.org/social.org
#+FOLLOW: https://sachachua.com/social.org
#+FOLLOW: https://www.alessandroliguori.it/social.org
#+FOLLOW: https://cherryramatis.xyz/social.org
#+FOLLOW: https://shom.dev/social.org
#+FOLLOW: https://comacero.eu/social.org
#+FOLLOW: https://cybervalley.org/org-social-leandro/org-social.org
#+FOLLOW: https://concavi.net/social.org
#+FOLLOW: http://gemini.quietplace.xyz/~razzlom/social.org
#+FOLLOW: https://notxor.nueva-actitud.org/social.org
#+FOLLOW: https://codeberg.org/mester/CosasSociales/raw/branch/main/social.org
#+FOLLOW: https://www.draketo.de/social.org

#+GROUP: Emacs https://org-social-relay.andros.dev
#+GROUP: Org Social https://org-social-relay.andros.dev
#+GROUP: Org Mode https://org-social-relay.andros.dev
#+GROUP: Elisp https://org-social-relay.andros.dev
#+GROUP: Random https://org-social-relay.andros.dev

* Posts
**
:PROPERTIES:
:ID: 2025-10-11T15:54:00+0200
:END:

First post on Org Social!


**
:PROPERTIES:
:ID: 2025-10-11T16:29:40+0200
:LANG: 
:TAGS: 
:CLIENT: org-social.el
:MOOD: 
:END:

Adding a few details to my profile and testing out my first post from local to server!

**
:PROPERTIES:
:ID: 2025-10-12T06:24:45+0200
:LANG: en
:TAGS: org-social emacs-lisp configuration
:CLIENT: org-social.el
:MOOD: 🤨
:END:

Any advice configuring org-social.el with straight.el?

When I try to load the timeline I get the following: =Warning: Could not load org-social-ui module= Then I need to go and load the code in =org-socual-ui.el= and then I can use everything without problem. Any idea why this could be happening?

My config is very simple:
#+begin_src emacs-lisp
(use-package org-social
  :straight
  (:host github
   :type git
   :repo "tanrax/org-social.el"
   :branch "main")
  :custom
  (org-social-file "~/Projects/teoten.com/public/social.org")
  (org-social-relay "https://org-social-relay.andros.dev/")
  (org-social-my-public-url "https://teoten.com/social.org"))
#+end_src

**
:PROPERTIES:
:ID: 2025-10-12T06:47:14+0200
:CLIENT: org-social.el
:REPLY_TO: https://andros.dev/static/social.org#2025-10-11T17:14:24+0200
:MOOD: 👋
:END:


**
:PROPERTIES:
:ID: 2025-10-12T13:34:48+0200
:LANG: 
:TAGS: 
:CLIENT: org-social.el
:REPLY_TO: https://andros.dev/static/social.org#2025-10-12T10:51:54+0200
:MOOD: 
:END:

Still nothing. I have updated from branch main and I can see the 3 new lines from the commit =51dfaeb= in my local version of the package-install:

#+begin_src emacs-lisp
    ;; Add UI subdirectories to load-path
    (add-to-list 'load-path (expand-file-name "ui" org-social--root-dir))
    (add-to-list 'load-path (expand-file-name "ui/buffers" org-social--root-dir))
#+end_src

But I still keep having the exact same error.

The changes expand properly to the right path ="~/.emacs.d/straight/build/org-social/ui"= and I can see all the right files and directories cloned to ="straight/repos/org-social/"= BUT I cannot see the sub directory =/ui= in the ="straight/build/org-social/"=. I am not sure if this is exactly the issue because I still have the sym link to =org-social-ui.el= file in the build dir (although not compiled), and when I evaluate that file in Emacs I get access to all the UI functionality. So, for now I have changed the value of =org-social--root-dir= to my straight path for repos (=(defconst org-social--root-dir "~/.emacs.d/straight/repos/org-social.el/")=) directly in the source code and that solves the problem completely.

Maybe it would be a good idea to make it a =defcustom=? Although it shouldn't be necessary. I don't have experience with packages with sub directories but I use a few so, I can try to find some time during the week to see how they do it and try to solve it the proper way. Meanwhile, I hope all this info is useful. Let me know if you want me to transfer it all to an issue in the repo.

**
:PROPERTIES:
:ID: 2025-10-15T15:04:16+0200
:LANG: 
:TAGS: 
:CLIENT: org-social.el
:REPLY_TO: https://andros.dev/static/social.org#2025-10-12T15:48:09+0200
:MOOD: 
:END:

Sorry for the late answer. Sure I'll open the issue

**
:PROPERTIES:
:ID: 2025-10-15T15:15:02+0200
:LANG: 
:TAGS: 
:CLIENT: org-social.el
:REPLY_TO: https://rosaelefanten.org/social.org#2025-10-15T02:43:47+0200
:MOOD: 
:END:

I was having the same question. I am curious what the author [[org-social:https://andros.dev/static/social.org][andros]] has to say.

Personally, I would be good by removing older posts, every 6/12 months. I can imagine how this can create broken links and how some people would like to keep certain things (or all) forever. I have never liked that. I am of the opinion that the old things have to die for the new to come to life. We are already swimming in oceans of data and information anyway so, I would be happy to contribute to cleaning up the mess a little by having total control of my data and my posts. In any other social network I am never sure if my data was completely erased when I click delete.

**
:PROPERTIES:
:ID: 2025-10-17T06:32:10+0200
:LANG: 
:TAGS: 
:CLIENT: org-social.el
:REPLY_TO: https://thesolarprincess.site/social.org#2025-10-16T23:00:00-0300
:MOOD: 
:END:

Welcome!

**
:PROPERTIES:
:ID: 2025-10-18T05:31:54+0200
:LANG: 
:TAGS: 
:CLIENT: org-social.el
:REPLY_TO: https://thesolarprincess.site/social.org#2025-10-17T19:32:13-0300
:MOOD: 
:END:

I was thinking the same. I think it is a flaw in the UI. There are many little things missing or not complete. But it is also a very new package and overall, project. So, it is probably useful to raise an issue in the github repo if you think this is important. Help the project grow.

**
:PROPERTIES:
:ID: 2025-10-19T05:01:43+0200
:LANG: 
:TAGS: 
:CLIENT: org-social.el
:REPLY_TO: https://johnhame.link/social.org#2025-10-18T23:57:21+0100
:MOOD: 
:END:

Tomorrow I complete my first week with my first mechanic keyboard, a Corne V4. I am super happy with it so far. I am still typing quite slow but I like it a lot. Before I was having just normal membrane keyboards but I had enough. I was interested in the Digma Defy, but it is quite expensive so, I decided to try with something more affordable before doing such an investment. Right now I am so happy with the minimalist design of the Corne that I might stay there, but we will see. What I love the most is to have all my modifiers at the reach of my thumbs, it is a game changer.

By the way, I can see the poll wit the proper org - [ ] to C-c C-c mark but of course, one cannot edit somebody else post, nor it would make sense. But I was just wondering if there is an easier way to just "vote" in a poll? You know, rather than writing a post with your answer? But I guess that also makes no sense, right?

**
:PROPERTIES:
:ID: 2025-10-22T02:56:00+0200
:LANG: 
:TAGS: 
:CLIENT: org-social.el
:REPLY_TO: https://johnhame.link/social.org#2025-10-19T18:26:33+0100
:MOOD: 
:END:

I read and saw videos about how many layers you might meed. But all I need is 2 layers: The basic one for the letters and then a 2nd with the numbers, missing symbols and the few F-keys I use regularly. So I am basically using one mod key (tap-hold, yes) for that 2nd layer a bit as a shift key. I have it at the easiest reach of my right thumb. I have Ctrl to the same position of the left thumb. And then space and enter next to each. Alt is the last in my thumb row, t I have it somewhere else because some combinations are complicated there. I guess I still have to tune it. As for Super, it is at the internal 2-key section, where some corne have the little display.

So far I'm happy with that layout and I am very happy with the keyboard, even though I'm still getting used to it.
